services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    build:
      target: dev
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000
    command: >
      sh -c "sqlift up --path database/migrations &&
              uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    build:
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

networks:
  proxy:
    driver: bridge
