services:
  backend:
    build:
      context: backend
      target: prod
    container_name: backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=default"
      - "traefik.http.routers.backend.rule=Host(`${BASE_URL}`) && PathPrefix(`/api`)"
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      sh -c "sqlift up --path database/migrations &&
              uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: frontend
      target: prod
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=default"
      - "traefik.http.routers.frontend.rule=Host(`${BASE_URL}`)"
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  proxy:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.default.acme.tlschallenge=true"
      - "--certificatesresolvers.default.acme.email=${TLS_EMAIL}"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - letsencrypt:/letsencrypt
    restart: unless-stopped

volumes:
  letsencrypt:
    