services:
  backend:
    build:
      context: backend
      target: prod
    container_name: backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy

  frontend:
    build:
      context: frontend
      target: prod
    container_name: frontend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy

  proxy:
    image: nginx:stable-alpine3.20
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443

networks:
  proxy:
    driver: bridge