services:
  backend:
    build:
      context: backend
      target: prod
    container_name: backend
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "sqlift up --path database/migrations &&
              uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: frontend
      target: prod
    container_name: frontend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${BASE_URL}`)"
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"