services:
  backend:
    build:
      context: backend
      target: prod
    container_name: backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy
    command: >
      sh -c "sqlift up --path database/migrations &&
              uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: frontend
      target: prod
    container_name: frontend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy

  proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  proxy:
    driver: bridge