services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    build:
      target: dev
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    build:
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

  proxy:
    extends:
      file: docker-compose.yml
      service: proxy

networks:
  proxy:
    driver: bridge
